### ISSUE TITLE
Plotting FES as function of time

### ISSUE THREAD

**Issue by syleck** [spiwokv/metadynminer#12]
Hello, professor Spiwok!
First of all, thank you for a very useful tool!
I have two silly questions. 
The first one is "Is there any way to plot free energy as function of time? (for CV1 and CV2 separately, as well for the entire system)".
The socond is "How can I extract the frame corresponding to the energy minima of interest? Is any way to find this frame directly?" The only way that I can suppose from tutorial is to search it by the values of CVs.

**Comment by spiwokv** [comment]
Hi!
Q1: You mean something like:
for every step:
- calculate F = F + hill(CVs(step))
- calculate F(CVs(step))
?

Q2: Similar functionality is in our web-based tool http://metadyn.vscht.cz/

Vojtech

**Comment by syleck** [comment]
Thank you for the answer!
